accounts/urls.py
from django.urls import path,re_path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    re_path('register', views.register, name='register'),
    re_path('login', views.login, name='login'),
    re_path('logout', views.logout, name='logout'),
    re_path('dashboard', views.dashboard, name='dashboard'),
]

listings/urls.py
from django.urls import path
from listings import views

app_name = 'listings'

urlpatterns = [
    path('', views.index, name='listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    path('search', views.search, name='search'),
]

pages/urls.py
from django.urls import path
from pages import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

property_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_alerts.html
{% if messages %}
{% for message in messages %}
<div class="container" id="message">
	<div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
		<button type="button" class="close" data-dismiss="alert">
		<span area-hidden="true">&times;</span>
		</button>
		<strong>
			{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
			Error!
			{% else %}
			{{ message.tags| title }}
			{% endif %}
		</strong>
		{{ message }}
	</div>
</div>
{% endfor %}
{% endif %}

templates/partials/_footer.html
<!-- Footer -->
  <footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> <a href="https://tahmid-ni7.github.io/portfolio/" class="text-white">tahmid.ni7</a>
  </footer>

templates/partials/_navbar.html
{% load static %}
<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'pages:index' %}">
        <img src="{% static 'img/logo.png' %}" class="logo" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
          <li
          {% if '/' == request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
          >
            <a class="nav-link" href="{% url 'pages:index' %}">Home</a>
          </li>
          
          <li
          {% if 'listings' in request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
          >
            <a class="nav-link" href="{% url 'listings:listings' %}">Featured Properties</a>
          </li>
          
          <li
          {% if 'about' in request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
          >
            <a class="nav-link" href="{% url 'pages:about' %}">About</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li
          {% if 'dashboard' in request.path %}
            class="nav-item active mr-3"
          {% else %}
            class="nav-item mr-3"
          {% endif %}
          >
            <a class="nav-link" href="{% url 'accounts:dashboard' %}">
              <i class="fas fa-user"></i>
              Welcome <strong>{{user.username}}</strong> (Dashboard)</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}">
            <i class="fas fa-sign-in-alt"></i>
            Logout</a>
            <form action="{% url 'accounts:logout' %}" method="post" id="logout">
              {% csrf_token %}
              <input type="hidden">
            </form>
          </li>
          {% else %}
          <li
          {% if 'register' in request.path %}
            class="nav-item active mr-3"
          {% else %}
            class="nav-item mr-3"
          {% endif %}
          >
            <a class="nav-link" href="{% url 'accounts:register' %}">
              <i class="fas fa-user-plus"></i> Register</a>
          </li>
          <li
          {% if 'login' in request.path %}
            class="nav-item active mr-3"
          {% else %}
            class="nav-item mr-3"
          {% endif %}
          >
            <a class="nav-link" href="{% url 'accounts:login' %}">
              <i class="fas fa-sign-in-alt"></i>

              Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

templates/partials/_topnav.html
<!-- Top Bar -->
  <section id="top-bar" class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <i class="fas fa-phone"></i> (018)-555-5555
        </div>
        <div class="col-md-4">
          <i class="fas fa-envelope-open"></i> tahmid.ni7@gmail.com
        </div>
        <div class="col-md-4">
          <div class="social text-right">
            <a href="#">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#">
              <i class="fab fa-facebook"></i>
            </a>
            <a href="#">
              <i class="fab fa-linkedin"></i>
            </a>
            <a href="#">
              <i class="fab fa-instagram"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>